%YAML 1.1
---
# amqp configuration

amqp:
    model_gem_global:
        instances: 2
        subtopic: model_gem_global.25km.#
        mirror: True
        report_back: False
        accept: .*
        on_file:

local:
    radar_4km:
        source:
        on_file:
    radar_1km:
        source:
        on_file:
